### PR TITLE
Added scrolling support (Closes #28)

### LINKED ISSUE #28: Scroll web browser with VS Code window
It would be awesome if the Web Browser could scroll with VS Code.

### PR DESCRIPTION
**Pull request by alallier**
Try out this behavior and let me know what you think.

Where it gets a little weird is the browser height might not match the VS Code window height. So in the cases of a scroll I always use the text at the top of the VS Code window to scroll to in the browser.

I still have to support the cursor in this case because if the VS Code window they are typing in is taller and they click _out of view_ the web browser will be in the wrong spot. So if they click in a place I set it to scroll to that location (this was the default behavior).

Happy to make change if you want me to tweak the behavior!

(Closes #28)

### CODE REVIEW

**Comment by alallier** [comment]
@dbankier any idea if you want/will take this PR. If so is there anything you want me to tweak/touch up?

Not trying to pester you, just excited about the potential for this feature!

**Comment by dbankier** [comment]
Sorry, like most people in the world, other things have taken priority. I like the idea also but haven't had a change to review. Can you also add a configuration option so it can be turned on/off?

**Comment by alallier** [comment]
@dbankier totally understand! Yes I can add the configuration option for you.

**Comment by alallier** [comment]
@dbankier I added the scrolling option.

**Comment by dbankier** [comment]
Was just working on this one.
I'm getting the following error: `Property 'onDidChangeTextEditorVisibleRanges' does not exist on type 'typeof window'.`

**Comment by dbankier** [comment]
Don't worry about it.

**Pull request merged**
